server:
  port: 8080

spring:
  flyway: # Flyway 활성화
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    import: optional:file:.env[.properties]  # .env 파일 읽기
  application:
    name: musinsa-shop

  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/musinsa_shop?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: musinsa-shop-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # Email(JavaMailSender) Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    doc-expansion: none
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.musinsashop: DEBUG

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access-expire-ms: ${JWT_ACCESS_EXPIRE_MS}
  refresh-expire-ms: ${JWT_REFRESH_EXPIRE_MS}

# 주소검색 API 설정
kakao:
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_API_KEY}